### ISSUE TITLE
Issue with Elapsed, ETA and Remaining after upgrading OctoPrint-HomeAssistant Plugin

### ISSUE THREAD

**Issue by jegres1709** [e11en/ha-threedy-card#4]
Hello,

I´m facing a problem with invalid dates and wrong ETA via mqtt:
![image](https://github.com/e11en/ha-threedy-card/assets/101667335/272696ed-5591-44a8-ab51-1b181b19fd25)

reason is https://github.com/cmroche/OctoPrint-HomeAssistant/pull/108
Time will be shown as seconds. mreditor97 delivered a patch, but the formatted time is available in the attributes:
![image](https://github.com/e11en/ha-threedy-card/assets/101667335/b52c1631-d990-4a8c-813b-be4c9e53c213)
![image](https://github.com/e11en/ha-threedy-card/assets/101667335/87a3c585-fb9b-49e7-914b-6784017e295b)

is it possible to take the right time from the attributes or format it within the card?

Thank you!

**Comment by mreditor97** [comment]
I didn't know this card existed! Brilliant!

For the time being, it is possible to create yourself a template sensor, which converts the MQTT provided time (in seconds) to a timedelta, which allows for formatting in a pretty format. You could then use that template sensor within this card.

```yaml
template:
  - sensor:
      - name: Octoprint Formatted Time Left
        state: {{ timedelta(seconds=states('sensor.octoprint_time_left') | int(default=0)) }}
```

_This hasn't been tested yet_

I hope this helps!
